### ISSUE TITLE
Audio has long delay in being sent from server.

### ISSUE THREAD

**Issue by michaelbarkdoll** [neutrinolabs/pulseaudio-module-xrdp#24]
Hello, I've followed your guide on Ubuntu 19.04 with Xorg, SLIM and XFCE4.  XRDP was installed with this custom compiled pulseaudio module for xrdp.  

I'm experiencing large delays in audio when using the Remmina RDP connection to the XRDP server.  Upon initial login to the server and starting an audio feed and seeing pavumeter showing the signal levels of xrdp sink are outputting the audio has a 10-13 second audio delay.  As the time in the XRDP session increases, the delay becomes longer and longer.  If I log out and back in to start a new session the audio delay is back to the initial 10-13 seconds.

Also, if I close a session and reconnect to the preexisting session the audio delays are still there.  This leads me to believe the issue is on the server side.

Please let me know how to output any useful debug information.  Thanks!

**Comment by michaelbarkdoll** [comment]
Also, I wanted to note the issue still exists after reboot when fixing the other ubuntu issue listed in the issues area on github.

https://github.com/neutrinolabs/pulseaudio-module-xrdp/issues/23

**Comment by kann181** [comment]
i am also facing the same issue. any workaround ?

**Comment by michaelbarkdoll** [comment]
#cry

**Comment by metalefty** [comment]
Fix neutrinolabs/xrdp#1363 has been submitted.

**Comment by metalefty** [comment]
Should be fixed.

**Comment by acharintsev** [comment]
Good day.
Problem with long delay in being sent sound from server still exists.
Linux kernel: 4.19.66.
Version xrdp: 0.9.11.
Pulseaudio: 12.0.
Interestingly manifested. When starting audio playback on the server, a pause occurs. About 5-7 seconds. Such a feeling that for a long time the channel for redirecting sound to the RDP is established. If you start a constant sound stream (for example, a song in VLC), then system sounds and sound from YouTube begin to be transmitted from the server without pauses.

**Comment by melvinvermeeren** [comment]
Having the same issues on Debian buster, clean xrdp and pulseaudio-module-xrdp installation. Pulseaudio 12.2.

With Debian stretch all worked fine, since buster there is 5-10sec delay on the receiving side, using xfreerdp as a client. Pavucontrol shows the server-side mixer properly during playback, without delay. Hard to diagnose further.

**Comment by bobhwasatch** [comment]
I'm also having this issue on Debian Buster.

**Comment by acharintsev** [comment]
> Good day.
> Problem with long delay in being sent sound from server still exists.
> Linux kernel: 4.19.66.
> Version xrdp: 0.9.11.
> Pulseaudio: 12.0.
> Interestingly manifested. When starting audio playback on the server, a pause occurs. About 5-7 seconds. Such a feeling that for a long time the channel for redirecting sound to the RDP is established. If you start a constant sound stream (for example, a song in VLC), then system sounds and sound from YouTube begin to be transmitted from the server without pauses.

Temporarily solved the problem with a pause in the sound. Rolled back to Pulseaudio version 9.0.

**Comment by obious4u** [comment]
Facing the same issue On Ubuntu, Have any of you found any solution other then rolling back to Pulseaudio version 9.0?

**Comment by metalefty** [comment]
Finally fixed by #38

**Comment by mirabilos** [comment]
Still occurs with the client being Debian buster, xrdp module commit e9f78c4f3a93951c5cbb6b084c202b2b630a0b55, pulseaudio 12.2-4+deb10u1, xrdp 0.9.9-1

I have about three seconds delay between
- starting `mpg123 test.mp3`
- changing the volume
and hearing the effect.

(Also, no microphone in the other direction. We'll see why that is.)
